import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/app/component/Navbar'
import Provider from './component/Provider'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: ' Viewers',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="icon" type="image/png" href='/logo.png' />
        </head>
        <body className={inter.className}>
          <Provider>
            <Navbar />
            {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  )
}
